# Generated by Django 2.2.2 on 2020-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('tamano', models.TextField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.TextField(max_length=254)),
            ],
        ),
    ]
